name: Chromatic

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable corepack (for pnpm)
        # https://nodejs.org/api/corepack.html
        run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install Node.js dependencies with pnpm
        # https://pnpm.io/cli/install
        run: >
          pnpm install
          --frozen-lockfile

      - name: Build package
        run: >
          pnpm run build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
